containerd_version: 1.6.20

containerd_home: /opt/containerd
containerd_config_dir: "{{ containerd_home }}/config"
containerd_bin_dir: "{{ containerd_home }}/bin"

containerd_archive_url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz

containerd_config_content: |
  version = 2
  root = "/var/lib/containerd"
  state = "/run/containerd"
  oom_score = 0

  [grpc]
    max_recv_message_size = 16777216
    max_send_message_size = 16777216

  [debug]
    level = "info"

  [metrics]
    address = ""
    grpc_histogram = false

  [plugins]

    [plugins."io.containerd.grpc.v1.cri"]
      sandbox_image = "registry.k8s.io/pause:3.8"
      max_container_log_line_size = -1
      enable_unprivileged_ports = false
      enable_unprivileged_icmp = false

      [plugins."io.containerd.grpc.v1.cri".containerd]
        default_runtime_name = "runc"
        snapshotter = "overlayfs"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
            runtime_engine = ""
            runtime_root = ""
            base_runtime_spec = "{{ containerd_config_dir }}/cri-base.json"

            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              systemdCgroup = true
      
      [plugins."io.containerd.grpc.v1.cri".registry]
      
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
            endpoint = ["https://registry-1.docker.io"]


